openapi: 3.0.0
info:
  title: Black Formatter API
  version: 1.0.0
paths:
  /format_code:
    post:
      summary: Format Python code using Black.
      operationId: runBlackFormatter
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
                  description: The path to the Python file to format.
      responses:
        '200':
          description: Code formatted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Invalid request or Black formatting failed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
